[build]
  command = "npm run build"
  publish = ".next"
  environment = { OPENAI_API_KEY = "YOUR_API_KEY" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

